### ISSUE TITLE
Can't kill child processes anymore

### ISSUE THREAD

**Issue by majapw** [neekey/ps#50] opened 2017-03-28 00:40 UTC
`ps-node` seems to get stuck in an infinite loop. This change was introduced in v0.1.5. Pinning our version to v0.1.4 seem to fix the issue.

Here is where we make a call to `ps-node`:
https://github.com/Galooshi/happo/blob/c0edfc6353a58d369cc4ea2de6c4e017583f8b6a/src/server/closeDriver.js#L31

Whereas previously this ran successfully, now we get an infinite loop of the following message:
```
check kill success 2079 confident 0
check kill success result: 1
check kill success 2079 confident 0
check kill success result: 1
check kill success 2079 confident 0
check kill success result: 1
check kill success 2079 confident 0
check kill success result: 1
check kill success 2079 confident 0
check kill success result: 1
check kill success 2079 confident 0
check kill success result: 1
...
```

FYI @lencioni @trotzig

**Comment by majapw** [comment] 2017-03-28 00:42
The issue appears to be with the base case in this recursive method - https://github.com/neekey/ps/blob/657bcddff328b159e4cd438616d4f9756298e0c4/lib/index.js#L214:L231

**Comment by trotzig** [comment] 2017-03-28 07:35
Thanks for making me aware of this issue @majapw, and for providing a workaround. I was hoping any of the marionette/geckodriver bugs that led me into using ps-node would be resolved by now. But it looks like they're not: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1310992
https://github.com/mozilla/geckodriver/issues/285
😞 

We could lock [the ps-node version in happo](https://github.com/Galooshi/happo/blob/1bd43a3bfbe6d4ef78cf0c3af47a4778bbfe059c/packages/happo-target-firefox/package.json#L22), but I'll give folks here a chance to respond/fix first.

**Comment by neekey** [comment] 2017-03-28 07:58
Hi @majapw @trotzig thanks for reporting this issue. In `0.1.5` I replaced the kill with the built-in `process.kill()`, and the loop check is to ensure that the process is actually killed before the callback in called.

So the case here seems that the result of the process checking is always one process alive.

Before discussing about what is a better way to handle the callback, @majapw can you confirm whether the target process has been terminated? (just to make sure the problem is that the kill failed or the checking is wrong)

**Comment by trotzig** [comment] 2017-03-28 09:04
Looking at this a little closer, I have a few ideas how to proceed: 

1. We could send the `SIGKILL` signal when killing the process: 

```js
psNode.kill(pid, 'SIGKILL', (err) => {
 // ...
});
```

2. You could time out the process checking after a while and send down an error to avoid ending up in an infinite loop. 

@majapw would you be willing to explore (1) for happo?

**Comment by neekey** [comment] 2017-03-28 09:06
@trotzig the (2) is exactly what I was thinking about, but just wanted to confirm what exactly caused the infinite checking first

**Comment by majapw** [comment] 2017-03-30 15:51
@trotzig I can def explore (1) for happo. It'll take me a little while to get to it though (maybe early next week?).

**Comment by neekey** [comment] 2017-04-01 06:45
@majapw @trotzig I just create a PR to add the timeout support, https://github.com/neekey/ps/pull/51 you can take a look

**Comment by neekey** [comment] 2017-04-21 05:48
0.1.6 released https://github.com/neekey/ps/pull/48

**Closed by neekey** 2017-04-21 05:48 UTC
